// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/helm/chart_check": {
            "post": {
                "description": "kubeconfig을 사용하여 특정 헬름 차트 설치 여부 확인",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helm"
                ],
                "summary": "특정 헬름 차트 설치 여부 확인",
                "parameters": [
                    {
                        "description": "헬름 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HelmConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/helm/health": {
            "get": {
                "description": "kubeconfig을 사용하여 헬름 연결 검증",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helm"
                ],
                "summary": "헬름 연결 확인",
                "parameters": [
                    {
                        "description": "헬름 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HelmConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/helm/install": {
            "post": {
                "description": "kubeconfig을 사용하여 헬름 차트 설치",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "helm"
                ],
                "summary": "헬름 차트 설치",
                "parameters": [
                    {
                        "description": "헬름 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.HelmInstallChartRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/kube/health": {
            "get": {
                "description": "kubeconfig을 사용하여 쿠버네티스 클러스터 연결 검증",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kubernetes"
                ],
                "summary": "쿠버네티스 클러스터 연결 확인",
                "parameters": [
                    {
                        "description": "쿠버네티스 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KubeConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/kube/pods": {
            "get": {
                "description": "kubeconfig을 사용하여 쿠버네티스 파드 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kubernetes"
                ],
                "summary": "쿠버네티스 파드 목록 조회",
                "parameters": [
                    {
                        "description": "쿠버네티스 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KubeConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/minio/bucket_check": {
            "post": {
                "description": "MinioConfig을 사용하여 Minio 버킷 존재 여부 확인 후, 없으면 생성",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "Minio 버킷 확인",
                "parameters": [
                    {
                        "description": "Minio 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MinioConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/minio/health": {
            "get": {
                "description": "MinioConfig을 사용하여 Minio 연결 검증",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "minio"
                ],
                "summary": "Minio 연결 확인",
                "parameters": [
                    {
                        "description": "Minio 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.MinioConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/backup-repositories": {
            "get": {
                "description": "MinioConfig, KubeConfig을 사용하여 Velero 백업 저장소 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 백업 저장소 목록 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VeleroConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/backup-storage-locations": {
            "get": {
                "description": "MinioConfig, KubeConfig을 사용하여 Velero 백업 스토리지 위치 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 백업 스토리지 위치 목록 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VeleroConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/backups": {
            "post": {
                "description": "MinioConfig, KubeConfig을 사용하여 Velero 백업 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 백업 목록 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VeleroConfigRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/health": {
            "get": {
                "description": "KubeConfig을 사용하여 Velero 연결 검증",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 연결 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.KubeConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/restores": {
            "get": {
                "description": "MinioConfig, KubeConfig을 사용하여 Velero 복구 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 복구 목록 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VeleroConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/velero/volume-snapshot-locations": {
            "get": {
                "description": "MinioConfig, KubeConfig을 사용하여 Velero 볼륨 스냅샷 위치 목록 조회",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "velero"
                ],
                "summary": "Velero 볼륨 스냅샷 위치 목록 확인",
                "parameters": [
                    {
                        "description": "Velero 연결에 필요한 값",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.VeleroConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "연결 성공",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerSuccessResponse"
                        }
                    },
                    "400": {
                        "description": "잘못된 요청",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "500": {
                        "description": "서버 내부 오류",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    },
                    "503": {
                        "description": "서비스 이용 불가",
                        "schema": {
                            "$ref": "#/definitions/models.SwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.HelmConfigRequest": {
            "type": "object",
            "required": [
                "chartName",
                "kubeconfig"
            ],
            "properties": {
                "chartName": {
                    "description": "[옵션] 헬름 차트 명",
                    "type": "string",
                    "example": "podinfo"
                },
                "kubeconfig": {
                    "description": "[필수] Base64 인코딩된 KubeConfig 값",
                    "type": "string",
                    "example": "base64 인코딩된 KubeConfig 값"
                }
            }
        },
        "models.HelmInstallChartRequest": {
            "type": "object",
            "required": [
                "chartName",
                "kubeconfig"
            ],
            "properties": {
                "chartName": {
                    "description": "[옵션] 헬름 차트 명",
                    "type": "string",
                    "example": "podinfo"
                },
                "kubeconfig": {
                    "description": "[필수] Base64 인코딩된 KubeConfig 값",
                    "type": "string",
                    "example": "base64 인코딩된 KubeConfig 값"
                },
                "namespace": {
                    "description": "[옵션] 네임스페이스 명 (기본 값 : 'default', 전체 조회  : 'all')",
                    "type": "string",
                    "example": "all"
                }
            }
        },
        "models.KubeConfig": {
            "type": "object",
            "properties": {
                "chartName": {
                    "description": "helm",
                    "type": "string"
                },
                "kubeconfig": {
                    "description": "Raw KubeConfig",
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "models.KubeConfigRequest": {
            "type": "object",
            "required": [
                "kubeconfig"
            ],
            "properties": {
                "kubeconfig": {
                    "description": "[필수] Base64 인코딩된 KubeConfig 값",
                    "type": "string",
                    "example": "base64 인코딩된 KubeConfig 값"
                },
                "namespace": {
                    "description": "[옵션] 네임스페이스 명 (기본 값 : 'default', 전체 조회  : 'all')",
                    "type": "string",
                    "example": "all"
                }
            }
        },
        "models.MinioConfig": {
            "type": "object",
            "properties": {
                "accessKey": {
                    "type": "string"
                },
                "bucketName": {
                    "type": "string"
                },
                "endpoint": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "secretKey": {
                    "type": "string"
                },
                "useSSL": {
                    "type": "boolean"
                }
            }
        },
        "models.MinioConfigRequest": {
            "type": "object",
            "required": [
                "accessKey",
                "endpoint",
                "secretKey",
                "useSSL"
            ],
            "properties": {
                "accessKey": {
                    "description": "[필수] minio accessKey",
                    "type": "string",
                    "example": "your_minio_accessKey"
                },
                "bucketName": {
                    "description": "[옵션] minio Bucket  (기본값: velero)",
                    "type": "string",
                    "example": "velero"
                },
                "endpoint": {
                    "description": "[필수] minio endpoint 주소",
                    "type": "string",
                    "example": "127.0.0.1:9000"
                },
                "region": {
                    "description": "[옵션] minio Region (기본값 : us-east-1)",
                    "type": "string",
                    "example": "us-east-1"
                },
                "secretKey": {
                    "description": "[필수] minio secretKey",
                    "type": "string",
                    "example": "your_minio_secretKey"
                },
                "useSSL": {
                    "description": "[필수] minio useSSL 여부 (false: http / true: https)",
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "models.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "models.SwaggerSuccessResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        },
        "models.VeleroConfig": {
            "type": "object",
            "properties": {
                "kubernetes": {
                    "$ref": "#/definitions/models.KubeConfig"
                },
                "minio": {
                    "$ref": "#/definitions/models.MinioConfig"
                }
            }
        },
        "models.VeleroConfigRequest": {
            "type": "object",
            "required": [
                "kubeconfig",
                "minio"
            ],
            "properties": {
                "kubeconfig": {
                    "description": "[필수] Base64 인코딩된 KubeConfig 값",
                    "type": "string",
                    "example": "base64 인코딩된 KubeConfig 값"
                },
                "minio": {
                    "$ref": "#/definitions/models.MinioConfigRequest"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9091",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "Velero API Server",
	Description:      "Velero backup and restore management API with multi-cluster support",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
