name: Generate Swagger

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Install swag
      run: go install github.com/swaggo/swag/cmd/swag@latest

    - name: Generate swagger docs
      run: swag init -g cmd/main.go -o docs/swagger --parseDependency --parseInternal

    - name: Commit and push if changed
      run: |
        git config user.name taking
        git config user.email taking@duck.com
        git add docs/swagger
        git diff --cached --quiet || git commit -m "Update swagger docs"
        git push
